name: pos-system # Nombre del proyecto en Docker

services:
  ordering-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pos-sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql # Aquí se guardan los datos físicos
    restart: unless-stopped
    networks:
      - pos-network
    # El Healthcheck verifica que SQL Server esté listo para recibir peticiones
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  mssql_data: # Definición del volumen

networks:
  pos-network: # Definición de la red interna
    driver: bridge